version: "3"
services:
  rails:
    image: rjnawara/mba-next:latest   
    volumes:
      - /home/ray/mba-orig-next:/mba-orig
    container_name: mba_rails
    depends_on:
      - mysql
    ports:
      - 8081:8080
    tty: true    
    environment:
      - RAILS_ENV=development

  mysql:
    image: vsamov/mysql-5.1.73
    volumes:
      - /home/ray/mba-mysql:/var/lib/mysql
    container_name: mba_mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=mba_development
      - MYSQL_ROOT_PASSWORD=Mys3267!
