version: "3"
services:
  rails:
    build: .   
    volumes:
      - ./mbadiamond:/mba-orig
    container_name: mba_rails
    depends_on:
      - mysql
      - gemstash
      - sphinx
    ports:
      - 8081:8080
    tty: true    
    environment:
      - RAILS_ENV=development

  mysql:
    image: vsamov/mysql-5.1.73
    volumes:
      - /home/ray/mba-mysql:/var/lib/mysql
    container_name: mba_mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=mba_development
      - MYSQL_ROOT_PASSWORD=Mys3267!

  gemstash:
    image: artemave/gemstash
    volumes: 
      - /home/ray/rails-next-docker:/root/.gemstash
    container_name: gemstash_server
    ports: 
      - '9292:9292'

  sphinx:
    image: ajoergensen/sphinxsearch
    volumes:
      - ./data:/var/lib/sphinxsearch/data
      - ./mbadiamond:/var/www/mbadiamond
      - ./sphinx.conf:/etc/sphinx/sphinx.conf
    container_name: sphinx-server
    mem_limit: 256m